### ISSUE TITLE
Problem with HSTS domains (e.g. *.dev)

### ISSUE THREAD

**Issue by Syndesi** [analogic/lescript#41]
Hi,

I'm using [Poste.io](https://poste.io/) which itself uses this library and I think the self-check [here](https://github.com/analogic/lescript/blob/f6a3bf0d47ef982805f90e2aea7d7cdf391c73cc/Lescript.php#L151) is failing for [HSTS-domains](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).
This is the log from running the script:
```txt
[2020-05-05 21:38:37] LEScript.INFO: Getting list of URLs for API
[2020-05-05 21:38:38] LEScript.INFO: Requesting new nonce for client communication
[2020-05-05 21:38:39] LEScript.INFO: Account already registered. Continuing.
[2020-05-05 21:38:39] LEScript.INFO: Sending registration to letsencrypt server
[2020-05-05 21:38:39] LEScript.INFO: Sending signed request to https://acme-v02.api.letsencrypt.org/acme/new-acct
[2020-05-05 21:38:40] LEScript.INFO: Account: https://acme-v02.api.letsencrypt.org/acme/acct/85344014
[2020-05-05 21:38:40] LEScript.INFO: Starting certificate generation process for domains
[2020-05-05 21:38:40] LEScript.INFO: Requesting challenge for mail.syndesi.dev
[2020-05-05 21:38:40] LEScript.INFO: Sending signed request to https://acme-v02.api.letsencrypt.org/acme/new-order
[2020-05-05 21:38:41] LEScript.INFO: Sending signed request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/4385366959
[2020-05-05 21:38:41] LEScript.INFO: Got challenge token for mail.syndesi.dev
[2020-05-05 21:38:41] LEScript.INFO: Token for mail.syndesi.dev saved at /opt/www//.well-known/acme-challenge/W9llQDn6tfhqBpdqaH4pwYkikDzQoL_XH9lkyaP0Gs8 and should be available at http://mail.syndesi.dev/.well-known/acme-challenge/W9llQDn6tfhqBpdqaH4pwYkikDzQoL_XH9lkyaP0Gs8
[2020-05-05 21:38:42] LEScript.ERROR: Please check http://mail.syndesi.dev/.well-known/acme-challenge/W9llQDn6tfhqBpdqaH4pwYkikDzQoL_XH9lkyaP0Gs8 - token not available
[2020-05-05 21:38:43] LEScript.ERROR: #0 /opt/admin/src/AppBundle/Handler/LeHandler.php(62): Analogic\ACME\Lescript->signDomains(Array)
[2020-05-05 21:38:43] LEScript.ERROR: #1 /opt/admin/src/AppBundle/Controller/LeController.php(71): AppBundle\Handler\LeHandler->renew(true)
[2020-05-05 21:38:43] LEScript.ERROR: #2 /opt/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): AppBundle\Controller\LeController->issueAction(Object(Symfony\Component\HttpFoundation\Request))
[2020-05-05 21:38:43] LEScript.ERROR: #3 /opt/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
[2020-05-05 21:38:43] LEScript.ERROR: #4 /opt/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
[2020-05-05 21:38:43] LEScript.ERROR: #5 /opt/admin/web/app.php(16): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
[2020-05-05 21:38:43] LEScript.ERROR: #6 {main}
```
The token itself is available at the url, can be checked with curl:
```bash
curl http://mail.syndesi.dev/.well-known/acme-challenge/W9llQDn6tfhqBpdqaH4pwYkikDzQoL_XH9lkyaP0Gs8
```

**Comment by Syndesi** [comment]
P.S.: Sry, I didn't reallize that analogic is behind poste.io ^^
Thank you very much for the great mail server, everything beside this is running great :D

**Comment by Syndesi** [comment]
I was able to request certificates successfully by disabling the if-clause.
